language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install . && pip install -r test_requirements.txt
script:
  - ./linters.sh && pytest --cov usfm_references --cov-report term-missing tests/
after_success:
  - coveralls
